### ISSUE TITLE
mulled* errors

### ISSUE THREAD

**Issue by rsuchecki** [galaxyproject/galaxy-lib#156]
I've attended the recent @bgruening talk at nf-core hackathon - amazing work of all involved. I can see e.g. multiple containers generated on travis but no luck so far with some of the mulled* tools from this repo. I've tried both conda and pip installation, different virtual environments, python versions but to no avail. Ironically even the associated biocontainer does not play ball. 

Is there a fool-proof way of getting this to work on a local (linux) machine?

```
docker run -it quay.io/biocontainers/galaxy-lib:19.5.2--py_0 mulled-search -s bwa -o biocontainers
Traceback (most recent call last):
  File "/usr/local/bin/mulled-search", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/galaxy/tools/deps/mulled/mulled_search.py", line 126, in main
    quay.build_index()
  File "/usr/local/lib/python3.7/site-packages/galaxy/tools/deps/mulled/mulled_search.py", line 42, in build_index
    r = requests.get(QUAY_API_URL, headers={'Accept-encoding': 'gzip'}, params=parameters,
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by mvdbeek** [comment]
galaxy-lib is pretty much unmaintained now and the mulled commands are part of galaxy-tool-util https://pypi.org/project/galaxy-tool-util/, which comes with the `requests` library that is missing in your example.
`pip install galaxy-tool-util Whoosh` should work now, I'll make sure we add Whoosh as well so that this will work.

**Comment by bgruening** [comment]
@rsuchecki can you please try: `conda create -n galaxy galaxy-tool-util`
