### ISSUE TITLE
from .container_resolvers.explicit import ExplicitContainerResolver

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy-lib#16]
See https://github.com/galaxyproject/planemo/issues/582 where TravisCI builds are failing ``planemo conda_init`` with:

<details>
```
$ planemo conda_init
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/bin/planemo", line 7, in <module>
    from planemo.cli import planemo
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/cli.py", line 11, in <module>
    from planemo.galaxy import profiles
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/galaxy/__init__.py", line 5, in <module>
    from .config import galaxy_config
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/galaxy/config.py", line 25, in <module>
    from planemo.docker import docker_host_args
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/docker.py", line 8, in <module>
    from galaxy.tools.deps.dockerfiles import docker_host_args
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/galaxy/tools/deps/dockerfiles.py", line 6, in <module>
    from ..deps.containers import docker_cache_path
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/galaxy/tools/deps/containers.py", line 15, in <module>
    from .container_resolvers.explicit import ExplicitContainerResolver
ImportError: No module named container_resolvers.explicit
```
<detail>

**Comment by martenson** [comment]
this should be already fixed with latest galaxy-lib release - maybe you need to update it

**Comment by martenson** [comment]
this fixed it imo: https://github.com/galaxyproject/galaxy-lib/commit/709cea80046bcbcc6cef45f803b78a5514fb6da7
